### ISSUE TITLE
Debug register values

### ISSUE THREAD

**Issue by Fraserbc** [nlscc/u8dbg_hdl#1]
Hi,
When reading the chipid, 0xAAFE is written to debug register 0x00. How did you come across these values, is there any documentation of them anywhere? Or did you have to extract these values from the U8 Dev Tools?

**Comment by Fraserbc** [comment]
@nlscc

**Comment by nlscc** [comment]
hi, sorry for missing your question, I used a logic analyzer to monitor the values read / written and then confirmed them by looking at the disassembly of a firmware update for the hardware debugger (i think it was called uease) since the MCU was locked. there's absolutely no docs on this so everything had to be reverse-engineered!

**Comment by nlscc** [comment]
also, the 0xaafe is just a magic value to unlock the debug interface and let you read/write other registers. this was yeaarrs ago but I was trying to connect to the MCU on a casio calculator but gave up since the chip seemed to need some kind of password before it would do anything useful (except let me read the chip ID!).

**Comment by Fraserbc** [comment]
Thanks so much! That's actually exactly what I (and some others are trying to do), we're trying to reverse engineer some casio calculators. Currently I'm going through exactly what you're doing, reverse engineering the EASE1000 firmware. By any chance do you still have any of those logic analyzer captures?
